### PR TITLE
Merge with imgareaselect master

### PR DESCRIPTION
**Pull request by darkdark87**
First, thanks for this really useful extension!
Could be really nice if you could merge it with the master branch, in order to have jQuery 1.9 support.

### CODE REVIEW

**Comment by fluke** [comment]
This repo seems to be unmaintained can we have someone else compile all the pull requests and moderate.

**Comment by azr** [comment]
@samuelcole seems to be the one maintaining this lib now https://github.com/samuelcole/imgareaselect

**Comment by azr** [comment]
In fact no, his version of master is broken. Is anyone maintaining it ?

**Comment by samuelcole** [comment]
Yeah, I haven't tried my fork out in production or anything. I think I had tests passing? But yeah, it's not to be trusted right now...

**Pull request closed without merging**
